language: java
jdk:
  - oraclejdk8

script: ./gradlew build --continue

after_success:
  - ./gradlew jacocoTestReport coveralls

notifications:
  slack:
    secure: "X+mFNL4Tw4wHrQZAyqli8XWTjgkrxt3tAcTjUeu7fUXDgGtx1PHIc4IS1+6PDlZemPNEaeYPv0i7a2CIpLoyi2dgw+1SWnSZQ2unj+rXbQtARS01D4zWPbGmUW7pnrbCEU8PtP0LU22/040TZetIwrD1yvS4Phi53CEMGvsoxfOmZQH4uh09IIeAX6ErvPXUxP8t3Nj6CF0urkWHwLaVgWqZxfXRa+ElD6z2certcs57CqWs0/ZH3dGlZ1QlZglw1U+GRQlrYn1A42HKGlXlO3+Ug1d6lgqpzJHqGEkfu1j0GmJ0cLvzSWGIjbX+NB1TgtXONEaCPFTpTLu5UxphvK864+dtBtGMs7lSHrPh0LoRarTWvGVSQVF+FJH+bsUamhE9RP776H8hX7DsSbP1fETg2Zj5Kk8EIrT7auo6uWbqMIpqIXigDrjZ2W1g9mfRSaX6qp054vYOl+vi0aKS2WF0xK2ZmRUL+teZXjOOEbStmqH/skdCNkh44fhLIhy6vjtfY4A8CeqpSW5OTL0kLE/My5013i6lcodVni9PHalt8Y0pyjoaefTTzHnHYlR+gNOXhZY6LhzWq2GQKbIWePpdfW1WGO7t4/EJpYU5Q4arSfA81P+ntEeWNOz55jxYq2t5zY2Syv894dQnfOr7U3hiWDuc7JLbvuUFnJPZMRI="