
env:
  global:
    secure: "Knl4sQ7Ka0fLXG3Jlew9tnWQONj5GLe8ljayOjteY+T7g+BtXWdvvQWiRrBZCREZ3NBDNfg6l4GaPvaXLXoKWixOCH2g04Bb4YVPb3/KGdcDoEcMYP+9grUBFVtK1HKD22BOOy69XilhGLbX4yt0DC+eExMq5e8Z3v8+ABH3IxGhY70FllH1BWhRTT5vgOnMEaU+6ywLjPxbLyMudEQ4Uh94luPKMmudT1PBAdLtbUgHxAHNMRzHS56TKVeUx5tQoZW+iQ0/mbLjK9WmALQIsaTRwp9vlnGH3D97WPHUodO2EFPsW22S9829+HfsZLdkTeZL7VYo2ofEgU6ug1DcKF8Y7b5kJiZKHHyM26rdz1EguBc9N7DazJ4053dlRnDOnE2Ih7Etv10h4PElTw/CaW9wv3gVPtW0kC3+/9oANiwIbSKTBjO8HOPqP2pgOBsU6Ru/FDvzRbWyhWTdWKBEbLiDyh8MapwMzRSCqk1zfdeglj2ZlWrW9GuExmkicPawvSoYx4gz5nqTELAVLgyjveqn//QBVR37iw/PqO2+jIuqBTFRxNdVy5mcEvb7zKkETB7NqrF9qgBxd/xUvKNEwmMJ4RGb7QOpvYJ15LSw9bmnoP3YilwEBrpa7/0Kyo/OdI0KGpkwAWRnva9GbK99MlRlIzL/yFWwB7WADhZD+k0="

language: java
jdk:
  - oraclejdk8

script: ./gradlew build --continue

after_success:
  - ./gradlew jacocoTestReport coveralls

notifications:
  slack:
    secure: "X+mFNL4Tw4wHrQZAyqli8XWTjgkrxt3tAcTjUeu7fUXDgGtx1PHIc4IS1+6PDlZemPNEaeYPv0i7a2CIpLoyi2dgw+1SWnSZQ2unj+rXbQtARS01D4zWPbGmUW7pnrbCEU8PtP0LU22/040TZetIwrD1yvS4Phi53CEMGvsoxfOmZQH4uh09IIeAX6ErvPXUxP8t3Nj6CF0urkWHwLaVgWqZxfXRa+ElD6z2certcs57CqWs0/ZH3dGlZ1QlZglw1U+GRQlrYn1A42HKGlXlO3+Ug1d6lgqpzJHqGEkfu1j0GmJ0cLvzSWGIjbX+NB1TgtXONEaCPFTpTLu5UxphvK864+dtBtGMs7lSHrPh0LoRarTWvGVSQVF+FJH+bsUamhE9RP776H8hX7DsSbP1fETg2Zj5Kk8EIrT7auo6uWbqMIpqIXigDrjZ2W1g9mfRSaX6qp054vYOl+vi0aKS2WF0xK2ZmRUL+teZXjOOEbStmqH/skdCNkh44fhLIhy6vjtfY4A8CeqpSW5OTL0kLE/My5013i6lcodVni9PHalt8Y0pyjoaefTTzHnHYlR+gNOXhZY6LhzWq2GQKbIWePpdfW1WGO7t4/EJpYU5Q4arSfA81P+ntEeWNOz55jxYq2t5zY2Syv894dQnfOr7U3hiWDuc7JLbvuUFnJPZMRI="